services:
  dagster_code_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagster_code_server
    command: >
      dagster code-server start 
      -h 0.0.0.0 
      -p 4000 
      -m iag.definitions
    environment:
      # Dagster configs
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      DAEMON_PORT: ${DAEMON_PORT}
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_POSTGRES_HOST: postgres
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${POSTGRES_DB}
      DAGSTER_POSTGRES_PORT: 5432
      PYTHONPATH: /opt/dagster/app/src

      # PROJECT VARIABLES
      DATA_PATH: /opt/dagster/data
      MARIADB_CONNECTION_STRING: ${MARIADB_CONNECTION_STRING}
      CONTRATOS_API_BASE_URL: ${CONTRATOS_API_BASE_URL}
      SQLSERVER_CONNECTION_STRING: ${SQLSERVER_CONNECTION_STRING}
      PCA_CONNECTION_STRING: ${PCA_CONNECTION_STRING}
      COMPRASGOV_API_BASE_URL: ${COMPRASGOV_API_BASE_URL}
      MONGO_DATABASE_URI: ${MONGO_DATABASE_URI}
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
      ORCID_SANDBOX: ${ORCID_SANDBOX}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      LAKEKEEPER_ENDPOINT: ${LAKEKEEPER_ENDPOINT}
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
      ENVIRONMENT: ${ENVIRONMENT:-production}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      WP_IAG_SITE_URL: ${WP_IAG_SITE_URL}
      WP_IAG_USERNAME: ${WP_IAG_USERNAME}
      WP_IAG_PASSWORD: ${WP_IAG_PASSWORD}
      ACESSO_API_URL: ${ACESSO_API_URL}
      ACESSO_API_USER: ${ACESSO_API_USER}
      ACESSO_API_PASSWORD: ${ACESSO_API_PASSWORD}
      HORUS_USERNAME: ${HORUS_USERNAME}
      HORUS_PASSWORD: ${HORUS_PASSWORD}
      HORUS_BASE_URL: ${HORUS_BASE_URL}
      TRINO_CONNECTION_STRING: ${TRINO_CONNECTION_STRING}
    volumes:
      - dagster_data:/opt/dagster/data
      - ./src/:/opt/dagster/app/src:ro
      - dagster_home:/opt/dagster/dagster_home
      - dagster_code_cache:/home/dagster/.cache
    networks:
      - dagster_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "dagster", "api", "grpc-health-check", "--host", "localhost", "--port", "4000"]
      interval: 7s
      timeout: 5s
      retries: 3

  dagster_daemon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagster_daemon
    command: dagster-daemon run -w /opt/dagster/dagster_home/workspace.yml
    environment:
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      DAEMON_PORT: ${DAEMON_PORT}
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_POSTGRES_HOST: postgres
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${POSTGRES_DB}
      DAGSTER_POSTGRES_PORT: 5432
      PYTHONPATH: /opt/dagster/app/src

      # PROJECT VARIABLES
      MARIADB_CONNECTION_STRING: ${MARIADB_CONNECTION_STRING}
      SQLSERVER_CONNECTION_STRING: ${SQLSERVER_CONNECTION_STRING}
      MONGO_DATABASE_URI: ${MONGO_DATABASE_URI}
      PCA_CONNECTION_STRING: ${PCA_CONNECTION_STRING}
      COMPRASGOV_API_BASE_URL: ${COMPRASGOV_API_BASE_URL}
      CONTRATOS_API_BASE_URL: ${CONTRATOS_API_BASE_URL}
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
      ORCID_SANDBOX: ${ORCID_SANDBOX}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      LAKEKEEPER_ENDPOINT: ${LAKEKEEPER_ENDPOINT}
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
      ENVIRONMENT: ${ENVIRONMENT:-production}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      DATA_PATH: /opt/dagster/data
      WP_IAG_SITE_URL: ${WP_IAG_SITE_URL}
      WP_IAG_USERNAME: ${WP_IAG_USERNAME}
      WP_IAG_PASSWORD: ${WP_IAG_PASSWORD}
      ACESSO_API_URL: ${ACESSO_API_URL}
      ACESSO_API_USER: ${ACESSO_API_USER}
      ACESSO_API_PASSWORD: ${ACESSO_API_PASSWORD}
      HORUS_USERNAME: ${HORUS_USERNAME}
      HORUS_PASSWORD: ${HORUS_PASSWORD}
      HORUS_BASE_URL: ${HORUS_BASE_URL}
      TRINO_CONNECTION_STRING: ${TRINO_CONNECTION_STRING}
    volumes:
      - dagster_data:/opt/dagster/data
      - ./src:/opt/dagster/app/src:ro
      - dagster_home:/opt/dagster/dagster_home
      - dagster_daemon_cache:/home/dagster/.cache
    networks:
      - dagster_network
    depends_on:
      postgres:
        condition: service_healthy
      dagster_code_server:
        condition: service_healthy
    restart: unless-stopped

  dagster_webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagster_webserver
    command: >
      dagster-webserver -h 0.0.0.0 -p ${WEBSERVER_PORT}
      -w /opt/dagster/dagster_home/workspace.yml
    environment:
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      DAEMON_PORT: ${DAEMON_PORT}
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_POSTGRES_HOST: postgres
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${POSTGRES_DB}
      DAGSTER_POSTGRES_PORT: 5432
      PYTHONPATH: /opt/dagster/app/src

      # Code variables
      MARIADB_CONNECTION_STRING: ${MARIADB_CONNECTION_STRING}
      CONTRATOS_API_BASE_URL: ${CONTRATOS_API_BASE_URL}
      SQLSERVER_CONNECTION_STRING: ${SQLSERVER_CONNECTION_STRING}
      MONGO_DATABASE_URI: ${MONGO_DATABASE_URI}
      PCA_CONNECTION_STRING: ${PCA_CONNECTION_STRING}
      COMPRASGOV_API_BASE_URL: ${COMPRASGOV_API_BASE_URL}
      DATA_PATH: /opt/dagster/data
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
      ORCID_SANDBOX: ${ORCID_SANDBOX}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      LAKEKEEPER_ENDPOINT: ${LAKEKEEPER_ENDPOINT}
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
      WP_IAG_SITE_URL: ${WP_IAG_SITE_URL}
      WP_IAG_USERNAME: ${WP_IAG_USERNAME}
      WP_IAG_PASSWORD: ${WP_IAG_PASSWORD}
      ACESSO_API_URL: ${ACESSO_API_URL}
      ACESSO_API_USER: ${ACESSO_API_USER}
      ACESSO_API_PASSWORD: ${ACESSO_API_PASSWORD}
      HORUS_USERNAME: ${HORUS_USERNAME}
      HORUS_PASSWORD: ${HORUS_PASSWORD}
      HORUS_BASE_URL: ${HORUS_BASE_URL}
      TRINO_CONNECTION_STRING: ${TRINO_CONNECTION_STRING}
    ports:
      - "${WEBSERVER_PORT:-3000}:${WEBSERVER_PORT}"
    volumes:
      - dagster_data:/opt/dagster/data
      - ./src:/opt/dagster/app/src:ro
      - dagster_home:/opt/dagster/dagster_home
      - dagster_webserver_cache:/home/dagster/.cache
    networks:
      - dagster_network
    depends_on:
      postgres:
        condition: service_healthy
      dagster_code_server:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: dagster_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dagster}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dagster}
      POSTGRES_DB: ${POSTGRES_DB:-dagster}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dagster_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dagster" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  dagster_data:
  postgres_data:
  dagster_home:
  dagster_code_cache:
  dagster_daemon_cache:
  dagster_webserver_cache:


networks:
  dagster_network:
    driver: bridge
